### ISSUE TITLE
Custom Swin Transformer: error: unrecognized arguments

### ISSUE THREAD

**Issue by AliKayhanAtay** [VcampSoldiers/Swin-Transformer-Tensorflow#3]
parser = argparse.ArgumentParser('Custom Swin Transformer')

parser.add_argument(
    '--cfg',
    type=str,
    metavar="FILE",
    help='/content/Swin-Transformer-Tensorflow/configs/swin_tiny_patch4_window7_224.yaml',
    default="CUSTOM_YAML_FILE_PATH"
)
parser.add_argument(
    '--resume',
    type=int,
    help=1,
    choices={0, 1},
    default=1,
)
parser.add_argument(
    '--weights_type',
    type=str,
    help='imagenet_22k',
    choices={"imagenet_1k", "imagenet_22k", "imagenet_22kto1k"},
    default="imagenet_1k",
)

args = parser.parse_args()
custom_config = get_config(args, include_top=False)

i am trying to use it but it throws an error below

usage: Custom Swin Transformer [-h] [--cfg FILE] [--resume {0,1}]
                               [--weights_type {imagenet_22kto1k,imagenet_1k,imagenet_22k}]
Custom Swin Transformer: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-ee309a98-1f20-4bb7-aa12-c2980aea076c.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by DHdroid** [comment]
Can you give us a more detailed description?
If you're running your code on jupyter, I recommend you follow [this](https://stackoverflow.com/questions/30656777/how-to-call-module-written-with-argparse-in-ipython-notebook) to use argparse.
